name: "Create Release"
description: "Create a release tag, generate release notes, create a release, update the README.md and open a PR for the README.md update."

inputs:
  release_tag:
    required: true
    type: string
  github_token:
    description: The Github token to authenticate PR operations.
    required: true
  reset_tag:
    type: boolean
    default: false
  release_notes_target:
    type: string
    default: "//release:generate_release_notes"
  update_readme_target:
    type: string
    default: "//release:update_readme"
  create_release_tag_target:
    type: string
    default: "@cgrindel_bazel_starlib//bzlrelease/tools:create_release_tag"
  base_branch:
    description: The branch being merged to.
    type: string
    default: main
  workspace_path:
    description: "The Bazel workspace directory."
    type: string
    default: ""
  repository:
    description: "The repository where the release should occur."

runs:
  using: composite
  steps:
    - uses: cgrindel/gha_configure_git_user@v1
      with:
        path: ${{ inputs.workspace_path }}

    - name: Create Release Tag
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RELEASE_TAG: ${{ inputs.release_tag }}
        RESET_TAG: ${{ inputs.reset_tag }}
        CREATE_RELEASE_TAG_TARGET: ${{ inputs.create_release_tag_target }}
        WORKSPACE_PATH: ${{ inputs.workspace_path }}
      run: |
        [[ -z "${WORKSPACE_PATH:-}" ]] || cd "${WORKSPACE_PATH}"
        tag_args=()
        [[ "${RESET_TAG:-}" == true ]] && tag_args+=( "--reset_tag" )
        tag_args+=( "${RELEASE_TAG}" )
        bazelisk run "${CREATE_RELEASE_TAG_TARGET}" -- "${tag_args[@]}"

    - name: Generate Release Notes
      id: generate_release_notes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RELEASE_TAG: ${{ inputs.release_tag }}
        RELEASE_NOTES_TARGET: ${{ inputs.release_notes_target }}
        WORKSPACE_PATH: ${{ inputs.workspace_path }}
      run: |
        [[ -z "${WORKSPACE_PATH:-}" ]] || cd "${WORKSPACE_PATH}"
        release_notes_path="${PWD}/release_notes.md"
        bazelisk run "${RELEASE_NOTES_TARGET}" -- \
          --output "${release_notes_path}" \
          "${RELEASE_TAG}"
        echo "::set-output name=release_notes_path::${release_notes_path}"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ inputs.release_tag }}
        body_path: ${{ steps.generate_release_notes.outputs.release_notes_path }}
        tag_name: ${{ inputs.release_tag }}
        token: ${{ inputs.github_token }}
        repository: ${{ inputs.repository }}

    - name: Update README.md
      shell: bash
      env:
        UPDATE_README_TARGET: ${{ inputs.update_readme_target }}
        RELEASE_TAG: ${{ inputs.release_tag }}
        README_PATH: ${{ inputs.readme_path }}
        WORKSPACE_PATH: ${{ inputs.workspace_path }}
      run: |
        [[ -z "${WORKSPACE_PATH:-}" ]] || cd "${WORKSPACE_PATH}"
        bazelisk run "${UPDATE_README_TARGET}" -- \
          --readme "${README_PATH}" \
          "${RELEASE_TAG}"

    - name: Create PR for README.md Update
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.github_token }}
        add-paths: |
          ${{ inputs.readme_path }}
        branch: auto_update_readme_for_${{ inputs.release_tag }}
        base: ${{ inputs.base_branch }}
        delete-branch: true
        title: Update REAMDE.md for ${{ inputs.release_tag }}
        body: Automated update of `${{ inputs.readme_path }}` for release ${{ inputs.release_tag }}
        path: ${{ inputs.workspace_path }}

    - name: Enable PR Automerge
      if: steps.create_pr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v1
      with:
        token: ${{ inputs.github_token }}
        pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
        merge-method: squash
        repository: ${{ inputs.repository }}
